don't use "using namespace std" in misc_filters.hpp
C++11 defines the class std::rank, which conflicts with Gamera's own
rank class.

This patch removes "using namespace std" from misc_filters.hpp and adds
"std:" in a few places where it was missing, which fixes the following
build failure:

    gamera/plugins/_misc_filters.cpp:167:14: error: reference to ‘rank’ is ambiguous
     return_arg = rank(*((Grey16ImageView*)self_arg), rank_arg, k_arg, border_treatment_arg);