don't define next() and prev() for C++11
C++11 (and later versions) provides the std::next() and std::prev()
functions, which are compatible with Gamera's functions of the same
names.

Defining next() and prev() conditionally fixes the following build
failure:

    include/rle_data.hpp:730:46: error: call of overloaded ‘next(std::__cxx11::list<Gamera::RleDataDetail::Run<short unsigned int>, std::allocator<Gamera::RleDataDetail::Run<short unsigned int> > >::iterator&)’ is ambiguous
        typename list_type::iterator next_i = next(i);